### ISSUE TITLE
incorporate the Costfunction-Script into polymer_elasticity

### ISSUE THREAD

**Issue by julianstar88** [CANTERhm/polymer_elasticity#13]
# General 
The only robust method for the evaluation of fits is to look directly to the Cost Function for different Parameter. This is important especially for Areas containing little Data and/ or much Parameter

# Roadmap for Enhancement
- [ ] add all Functions in the Script  *Costfunction* to the UtilityFunctions-Class of *polymer_elasticity*
- [ ] add a "Cost Function"-Tab to the slide panel
- [ ] the "Cost Function"-Tab must contain all adaptable Parameters of *Costfunction*
- [ ] bind the Script Procedure to the Button "Calculate Cost Function"
