### ISSUE TITLE
add "Do Fit" button to the modelparameter-tab on the slide-panel

### ISSUE THREAD

**Issue by julianstar88** [CANTERhm/polymer_elasticity#3]
# General
In order to enhance the performance of *polyer_elasticity* it seems to be more useful to perform the fit by pressing a button rather than listen to changes in the parameter-objects itself (*variable_parameter*, *constant_parameter*, and *hold_parameter*). This might cause errors and slows down the working efficiency if one evaluates a bunch of force-curve

# Roadmap to Enhancement
- [x] add a `uix.HButtonBox` to the *modelparameter-tab* on the *slide-panel* between *vary_parameter_table* and *constant_parameter_table*
- [x] add a `uicontrol()` Style 'pushbutton' to the `uix.HButtonBox` with the String 'Do Fit' (aligned to the right hand side of the *slide-panel*)
- [x] change the *callback-property* of the *Do Fit* button to the `Callbacks.DoFit()` function
- [x] delete all *event-listeneres* concerning the *vary_parameter*, *constant_parameter* and *hold_parameter* object-changes (not the *CellEditCallbacks* of the corresponding tables)

**Comment by julianstar88** [comment]
Still testing, before closing this issue.

**Comment by julianstar88** [comment]
Enough testing
