### ISSUE TITLE
enhancement of the workflow

### ISSUE THREAD

**Issue by julianstar88** [CANTERhm/polymer_elasticity#5]
# General
The problem is that, if you want to fit, one has to work with two axes. In the first one, you choose the point or the area of the baseline of the force curve. In the second one, you choose the fit range based on the corrected data of step one. This leads to the issue that if the user changes the baseline without choosing a new fit range, the fit range contains data with the wrong offset. Consecutively the fit also shows up with this wrong offset.

# Roadmap of Enhancement
- [x] User one axes for both, choosing the baseline area and choosing the fit range
- [x] The fit range has to be chosen from the original data, not from the corrected one
- [x] The offset calculated via the baseline area has to be applied additionally to the fit range, every time one will start a new fit (this means in the `Callbacks.DoFit()` function)
