### ISSUE TITLE
second results-table

### ISSUE THREAD

**Issue by julianstar88** [CANTERhm/polymer_elasticity#8]
# General
Currently, it´s not possible to obtain Information about x/y Offsets. This Information is important to know if someone wants to fit a force-curve again within the same conditions. To achieve this Goal, it is better to separate all the information as follows:
- one Table for the Fit parameters --> results_table
- one Tabel for Informations about the fitting conditions (fit range, fit borders, x/y offsets) --> results_table_2
- rearrange Data in results_table: set "Rupture Length" as the Last Value; set "Lc Fit" as the second one

# Roadmap for Enhancement
- [x] create a second table (results_table_2, uitable, no row names)
- [x] place it into the controls-VBox
- [x] update via `Callbacks.DoFit`
