### ISSUE TITLE
add a "Vocabulary" headline to the help-tab

### ISSUE THREAD

**Issue by julianstar88** [CANTERhm/polymer_elasticity#9]
# General
The reason why is to explain the used words. For Example, what´s the difference between "Rupture Lenght" and "Lc_Fit". 
# Roadmap for Enhancement
So Far add the following Entries:
- [x] Rupture Length: Lc_Fit + x-offset; it is the "Position" of the Rupture Event in the Coordinate System
- [x] Ks_Fit: means the fitted Segment Elasticity of the investigated Molecule 
- [x] Lc_Fit: means the fitted Contourlenght of the investigated Molecule
- [x] lk_Fit: means the fitted Kuhn length of the investigated Molecule
- [x] Xl: left border of the Fit Range in %
- [x] Xr: right border of the Fit Range in %
- [x] Distance: Distance between Xl and Xr (Xr-Xl) in %

**Comment by julianstar88** [comment]
This can be done in the Release for v 2.2.0

**Comment by julianstar88** [comment]
Call the vocabulary-headline "Terminology"
